version: '3.8'
# command: docker compose up --build
# https://medium.com/@jewelski/quickly-set-up-a-local-postgres-database-using-docker-5098052a4726
# https://www.docker.com/blog/how-to-use-the-postgres-docker-official-image/#Why-should-you-containerize-Postgres
# https://github.com/docker/awesome-compose/tree/master/postgresql-pgadmin
# docker compose -f .docker/compose.yaml up
# docker compose -f .docker/compose.yaml down
services:
#  youcode-app:
#    build:
#      context: ../ 
#      dockerfile: ./Dockerfile 
#    container_name: youcode-app
#    environment:
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PW}
#      - POSTGRES_DB=${POSTGRES_DB} #optional (specify default database instead of $POSTGRES_DB)
#    ports:
#      - "3000:3000"
#    restart: unless-stopped
  postgres:
    container_name: node-sandbox
    image: postgres:15.5-alpine3.18
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB} #optional (specify default database instead of $POSTGRES_DB)
    hostname: localhost
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: youcode-pgadmin
    image: dpage/pgadmin4:latest
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    restart: unless-stopped

volumes:
  postgres-data:
networks:
  youcode-netw²rk:
    external: true